### ISSUE TITLE
Add functionality to `bring-me add`

### ISSUE THREAD

**Issue by 4tydev** [devasolutions/bring-me#13]
#### Description:
If `add` with no arguments is executed, then the program downloads a random popular library from jsdelivr.com
#### Tasks:
- [ ] Include jsdelivr API
- [ ] check popular packages
- [ ] download selected library
