### ISSUE TITLE
### bring-me rm command

### ISSUE THREAD

**Issue by 4tydev** [devasolutions/bring-me#7]
#### Description:
Create a command that removes a certain library from the bmconfig.json. Create --restart to restart the file to default. If rm comes with no arguments, then the whole file is deleted.
#### Tasks:
- [x] Add rm command to the program.
- [x] add optional arguments with name and version
- [x] No arguments received, delete the CONTENTS OF THE FILE, DONT DELETE THE FILE.
- [x] Add -r, --restart option to command
- [x] create rm function and file
