### ISSUE TITLE
### Check if library and version exists

### ISSUE THREAD

**Issue by 4tydev** [devasolutions/bring-me#8]
#### Description:
In the add command, you have to check if the given library and version exists or not.
#### Tasks:
- [x] Check if library exists
- [x] If library and version exists in bmconfig.json, tell user that library already exist
- [x] if library and version doesn't exist, then add library to bmconfig.json
