### ISSUE TITLE
### Edit README.md

### ISSUE THREAD

**Issue by 4tydev** [devasolutions/bring-me#9]
#### Description:
The README.md documentation is outdated and needs to include the new functionalities and conditions.
#### Tasks:
- [x] Add clause that states that the bmconfig.json HAS to be inside the module directory
- [x] Edit the add command and delete the addCdn command
- [x] Include new documentation for the commands
